name: Ejecutar RD

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * 0' # Ejecuta todos los domingos a las 8 PM UTC timesz

jobs:
  execute-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Instalar dependencias
      run: npm install
    - name: Ejecutar script
      env:
        CONSUMER1: ${{ secrets.CONSUMER1 }} 
        SOL1: ${{ secrets.SOL1 }}
      run: node index.js

